services:
  - type: web
    name: medimate
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: ./run_on_render.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: medimate.settings
      - key: RENDER
        value: true

