# Generated by Django 5.2.4 on 2025-07-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='next_dose_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
