# Generated by Django 5.2.4 on 2025-07-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicine_next_dose_time_alter_medicine_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
